# Not necessary, could be deprecated
apiVersion: v1
kind: Secret
metadata:
  name: freelancer-secret
type: Opaque
stringData:
  MYSQL_DATABASE: ${MYSQL_DATABASE}   
  MYSQL_USER:  ${MYSQL_USER}                     
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}           
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  SPRING_DATA_MONGODB_URI : ${SPRING_DATA_MONGODB_URI}